### ISSUE TITLE
Add driver adjustable settings to lap_data

### ISSUE THREAD

**Issue by redburningice** [msundstrom/ACCStatsUploader#23]
Add the following electronic settings to the tool:

- TC and TC2 level
- ABS level
- Brake Bias
- Fuel Map

**Comment by msundstrom** [comment]
On the lap data sheet?

**Comment by redburningice** [comment]
Yes! Might be worth it if you have consistent changes throughout a stint (e.g. changing brake balance, because car balance changes after X laps)

**Comment by msundstrom** [comment]
Agreed! Might be tricky to figure out how to display it however 🧐

**Comment by msundstrom** [comment]
When would you track this? End of lap, beginning of lap?

**Comment by redburningice** [comment]
I guess it doesn't really matter, but end of lap I'd say
