### ISSUE TITLE
Add engine map to lap data

### ISSUE THREAD

**Issue by msundstrom** [msundstrom/ACCStatsUploader#27]

**Comment by msundstrom** [comment]
I think we can add it as a percentage list, maybe. Let's say the output would look something like this:
`1(10%), 2(20%),1(70%)`

That probably isn't very "parseable" though, so maybe there's a better way 🤔

**Comment by redburningice** [comment]
related to #23

**Comment by redburningice** [comment]
I thought about doing it like this:
`1:0.10, 2:0.70, 3:0.20`
This is more parseable, but probably worse for humans 🤔

**Comment by msundstrom** [comment]
It's not an either/or thing either tbh, we could have both.
